ruby_on_rails/config/routes.rb
EvernoteSample::Application.routes.draw do
  root :to => 'home#index'

  get '/modes/switch' => 'home#switch_mode', :as => 'switch_mode'

  get '/auth/:provider/callback' => 'login#callback'
  get '/logout' => 'login#logout', :as => 'logout'
  get '/oauth_failure' => 'login#oauth_failure'

  get 'user_store/:method' => 'user_store#call', :as => 'user_store'
  get 'note_store/:method' => 'note_store#call', :as => 'note_store'
  get 'advanced/:method' => 'advanced#call', :as => 'advanced'
end

ruby_on_rails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @available_us_methods = UserStoreController.private_instance_methods(false).select{|m|
      !m.to_s.start_with?('_')
    }
    @unavailable_us_methods =
      Evernote::EDAM::UserStore::UserStore::Client.instance_methods(false).select{|m|
      !m.to_s.match(/send_|recv_/)
    }.sort - @available_us_methods

    @available_ns_methods = NoteStoreController.private_instance_methods(false).select{|m|
      !m.to_s.start_with?('_')
    }
    @unavailable_ns_methods =
      Evernote::EDAM::NoteStore::NoteStore::Client.instance_methods(false).select{|m|
      !m.to_s.match(/send_|recv_/)
    }.sort - @available_ns_methods
    @available_advanced_methods = AdvancedController.private_instance_methods(false).select{|m|
      !m.to_s.start_with?('_')
    }
  end

  def switch_mode
    session[:dry_run] = !session[:dry_run]
    redirect_to :root
  end

end

ruby_on_rails/app/helpers/home_helper.rb
module HomeHelper
end

ruby_on_rails/app/views/home/_api_list.html.haml
%h2 Sample Use Cases
%ul
  - @available_advanced_methods.each do |m|
    %li= link_to_advanced m

%h2 Basic Usage of UserStore
%ul
  - @available_us_methods.each do |m|
    %li= link_to_user_store m
- unless @unavailable_us_methods.blank?
  %h4 Not implemented
  %ul
    - @unavailable_us_methods.each do |m|
      %li= m

%h2 Basic Usage of NoteStore
%ul
  - @available_ns_methods.each do |m|
    %li= link_to_note_store m
- unless @unavailable_ns_methods.blank?
  %h4 Not implemented
  %ul
    - @unavailable_ns_methods.each do |m|
      %li= m

-# For NoteStore#createLinkedNotebook, NoteStore#createSharedNotebook
- ['createLinkedNotebook', 'createSharedNotebook'].each do |m|
  %div{id: "#{m}-form", title: "Type your email address"}
    = form_tag do
      %fieldset
        = label_tag "email"
        = text_field_tag "email", '',
          :class => "text ui-widget-content ui-corner-all", :id => "email-#{m}", :size => 30

  :javascript
    $("##{m}-form").dialog({
      autoOpen: false,
      height: 220,
      width: 400,
      modal: true,
      buttons: {
        Proceed: function() {
          window.location =
            $('#note_store_#{m}').attr('href') + '?email=' + $("#email-#{m}").val();
        },
        Cancel: function() {
          $( this ).dialog( "close" );
        }
      }
    });
    $("##{m}-form").keypress(function(e) {
      if (e.keyCode == $.ui.keyCode.ENTER) {
        window.location =
          $('#note_store_#{m}').attr('href') + '?email=' + $("#email-#{m}").val();
        return false;
      }
    });
    $("#note_store_#{m}").bind('click', function() {
      $("##{m}-form").dialog("open");
      return false;
    });

ruby_on_rails/app/views/home/api_result.html.haml
= link_to 'Back to the list', root_path
%hr
%h2= "#{controller_name.classify}##{params[:method]}"
%h2 Code
= CodeRay.scan(@code, :ruby).div(:line_numbers => :table).html_safe
%h2 Result
- if params[:method] == 'getResourceData'
  %img{:src => "data:image/png;base64,#{[@result].pack('m')}"} 
  = CodeRay.scan(truncate(@result.inspect, length: 100), :ruby).div.html_safe
- else
  = CodeRay.scan(@result.inspect, :ruby).div.html_safe
- if @note
  %h2 Note
  = auto_link @note
- if @doc && @doc_url
  %h2 Document
  = link_to 'API Document', @doc_url
  = @doc.html_safe

ruby_on_rails/app/views/home/index.html.haml
- if ENV['EN_CONSUMER_KEY'].blank? || ENV['EN_CONSUMER_SECRET'].blank?
  %h2 You have to set your Evernote Consumer Key and Consumer Secret in you environmental variables first.
  %ul
    %li= "EN_CONSUMER_KEY: #{ENV['EN_CONSUMER_KEY']}"
    %li= "EN_CONSUMER_SECRET: #{ENV['EN_CONSUMER_SECRET']}"

- elsif authtoken
  = link_to (session[:dry_run] ? "Allow actual API call" : "Prohibit actual API call"), switch_mode_path
  |
  = link_to 'Logout', logout_path
  %hr
  = render 'api_list'
- else
  = link_to 'Login via Evernote', '/auth/evernote'